### ISSUE TITLE
The backlight of the monitor starts with a delay.

### ISSUE THREAD

**Issue by ghost** [helmimarif/Hackintosh-MSI-Modern14#2]
Hello! I used your config, everything works fine, but there was a problem. When the computer starts, the backlight works in UEFI, but then turns off for 2-3 minutes at the account login screen. Have you encountered this problem and how did you solve it?

**Comment by vitokate** [comment]
Hi,

did you managed to solve it?

**Comment by ghost** [comment]
Unfortunately not, I tried to update the kexts and dig into the config, without success.

**Comment by helmimarif** [comment]
Already fixed with the latest [WhateverGreen](https://github.com/acidanthera/WhateverGreen/releases/). Add `-igfxblr`, `-igfxbls`, `-igfxblt`, and `igfxonln=1` to boot-args.
